steps:
  - name: 'docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${_SERVICE}', '.']

  - name: 'docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/${_SERVICE}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', '${_SERVICE}',
           '--platform', 'managed', '--region', '${_REGION}',
           '--image', 'gcr.io/${PROJECT_ID}/${_SERVICE}']

substitutions:
 _REGION: us-central1
 _SERVICE: myservice
